[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["openai", "nodemailer"]
  node_bundler = "esbuild"
  included_files = ["app/api/**", "lib/**"]
